# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/WHT_Project_Rain3/wht.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(928, 596)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(570, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Math TeX Gyre"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(720, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Math TeX Gyre"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(590, 90, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 911, 451))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 20, 101, 20))
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_8.setFrame(True)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(350, 20, 101, 20))
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(240, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(500, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(630, 20, 101, 21))
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.checkBox_11 = QtGui.QCheckBox(self.tab)
        self.checkBox_11.setGeometry(QtCore.QRect(770, 10, 61, 41))
        self.checkBox_11.setText(_fromUtf8(""))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.comboBox_6 = QtGui.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 70, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.setItemText(0, _fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(240, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab)
        self.lineEdit_11.setGeometry(QtCore.QRect(350, 70, 101, 21))
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(500, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.comboBox_7 = QtGui.QComboBox(self.tab)
        self.comboBox_7.setGeometry(QtCore.QRect(630, 70, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.pushButton_23 = QtGui.QPushButton(self.tab)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(120, 130, 321, 31))
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.pushButton_24 = QtGui.QPushButton(self.tab)
        self.pushButton_24.setGeometry(QtCore.QRect(470, 130, 111, 31))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(self.tab)
        self.pushButton_25.setGeometry(QtCore.QRect(630, 130, 111, 31))
        self.pushButton_25.setAccessibleName(_fromUtf8(""))
        self.pushButton_25.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(10, 200, 111, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab)
        self.lineEdit_13.setGeometry(QtCore.QRect(120, 200, 321, 41))
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(10, 270, 91, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tab)
        self.lineEdit_14.setGeometry(QtCore.QRect(120, 270, 121, 21))
        self.lineEdit_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(10, 340, 101, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_15 = QtGui.QLineEdit(self.tab)
        self.lineEdit_15.setGeometry(QtCore.QRect(120, 340, 121, 21))
        self.lineEdit_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(280, 270, 81, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab)
        self.lineEdit_16.setGeometry(QtCore.QRect(370, 270, 121, 21))
        self.lineEdit_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(510, 270, 91, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tab)
        self.lineEdit_17.setGeometry(QtCore.QRect(610, 270, 121, 21))
        self.lineEdit_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(280, 340, 81, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_18 = QtGui.QLineEdit(self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(370, 340, 113, 20))
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(630, 100, 101, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 100, 61, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(800, 20, 101, 21))
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pushButton_25.raise_()
        self.label_16.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.lineEdit_10.raise_()
        self.checkBox_11.raise_()
        self.label_19.raise_()
        self.comboBox_6.raise_()
        self.label_20.raise_()
        self.lineEdit_11.raise_()
        self.label_21.raise_()
        self.comboBox_7.raise_()
        self.pushButton_23.raise_()
        self.lineEdit_12.raise_()
        self.pushButton_24.raise_()
        self.label_22.raise_()
        self.lineEdit_13.raise_()
        self.label_23.raise_()
        self.lineEdit_14.raise_()
        self.label_24.raise_()
        self.lineEdit_15.raise_()
        self.label_25.raise_()
        self.lineEdit_16.raise_()
        self.label_26.raise_()
        self.lineEdit_17.raise_()
        self.label_27.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_7.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.checkBox_12 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 0, 41, 31))
        self.checkBox_12.setText(_fromUtf8(""))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(40, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.comboBox_16 = QtGui.QComboBox(self.tab_2)
        self.comboBox_16.setGeometry(QtCore.QRect(470, 40, 171, 21))
        self.comboBox_16.setObjectName(_fromUtf8("comboBox_16"))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.lineEdit_31 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(470, 70, 221, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.pushButton_27 = QtGui.QPushButton(self.tab_2)
        self.pushButton_27.setGeometry(QtCore.QRect(720, 70, 81, 23))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.checkBox_20 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_20.setGeometry(QtCore.QRect(470, 110, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.pushButton_28 = QtGui.QPushButton(self.tab_2)
        self.pushButton_28.setGeometry(QtCore.QRect(720, 110, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.checkBox_21 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_21.setGeometry(QtCore.QRect(470, 190, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.pushButton_29 = QtGui.QPushButton(self.tab_2)
        self.pushButton_29.setGeometry(QtCore.QRect(720, 210, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.label_56 = QtGui.QLabel(self.tab_2)
        self.label_56.setGeometry(QtCore.QRect(470, 205, 241, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.lineEdit_32 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(465, 230, 21, 21))
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.label_57 = QtGui.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(490, 230, 21, 20))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.lineEdit_33 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_33.setGeometry(QtCore.QRect(500, 230, 21, 21))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.label_58 = QtGui.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(530, 230, 21, 21))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.lineEdit_34 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(540, 230, 21, 21))
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.lineEdit_35 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(580, 230, 21, 20))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.lineEdit_36 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(620, 230, 21, 20))
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.label_59 = QtGui.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(645, 230, 21, 20))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.lineEdit_37 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_37.setGeometry(QtCore.QRect(650, 230, 21, 20))
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.label_60 = QtGui.QLabel(self.tab_2)
        self.label_60.setGeometry(QtCore.QRect(675, 230, 21, 20))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.lineEdit_38 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_38.setGeometry(QtCore.QRect(690, 230, 21, 20))
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.label_61 = QtGui.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(470, 280, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.lineEdit_39 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_39.setGeometry(QtCore.QRect(582, 280, 51, 21))
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.label_62 = QtGui.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(470, 320, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.lineEdit_40 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_40.setGeometry(QtCore.QRect(580, 320, 51, 20))
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.pushButton_30 = QtGui.QPushButton(self.tab_2)
        self.pushButton_30.setGeometry(QtCore.QRect(490, 350, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.pushButton_31 = QtGui.QPushButton(self.tab_2)
        self.pushButton_31.setGeometry(QtCore.QRect(490, 380, 91, 23))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.label_63 = QtGui.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(640, 320, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.lineEdit_41 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_41.setGeometry(QtCore.QRect(720, 320, 51, 21))
        self.lineEdit_41.setObjectName(_fromUtf8("lineEdit_41"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(570, 110, 131, 20))
        self.lineEdit_4.setAccessibleName(_fromUtf8(""))
        self.lineEdit_4.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 451, 381))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(0, 0, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_19.setGeometry(QtCore.QRect(90, 0, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setText(_fromUtf8(""))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.label_43 = QtGui.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(260, 0, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.comboBox_13 = QtGui.QComboBox(self.groupBox)
        self.comboBox_13.setGeometry(QtCore.QRect(350, -1, 81, 21))
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(0, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(0, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(0, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.comboBox_8 = QtGui.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(120, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_9 = QtGui.QComboBox(self.groupBox)
        self.comboBox_9.setGeometry(QtCore.QRect(120, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_10 = QtGui.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(120, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.label_44 = QtGui.QLabel(self.groupBox)
        self.label_44.setGeometry(QtCore.QRect(240, 30, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox)
        self.label_45.setGeometry(QtCore.QRect(240, 60, 91, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.groupBox)
        self.label_46.setGeometry(QtCore.QRect(240, 80, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_22.setGeometry(QtCore.QRect(350, 30, 81, 20))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_23.setGeometry(QtCore.QRect(350, 60, 81, 21))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_24.setGeometry(QtCore.QRect(350, 90, 81, 21))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(0, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_20.setGeometry(QtCore.QRect(120, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.label_47 = QtGui.QLabel(self.groupBox)
        self.label_47.setGeometry(QtCore.QRect(240, 120, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_25.setGeometry(QtCore.QRect(350, 120, 81, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(0, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.comboBox_11 = QtGui.QComboBox(self.groupBox)
        self.comboBox_11.setGeometry(QtCore.QRect(120, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.label_48 = QtGui.QLabel(self.groupBox)
        self.label_48.setGeometry(QtCore.QRect(240, 150, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.comboBox_14 = QtGui.QComboBox(self.groupBox)
        self.comboBox_14.setGeometry(QtCore.QRect(350, 150, 71, 21))
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(0, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.comboBox_12 = QtGui.QComboBox(self.groupBox)
        self.comboBox_12.setGeometry(QtCore.QRect(120, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.label_49 = QtGui.QLabel(self.groupBox)
        self.label_49.setGeometry(QtCore.QRect(240, 170, 71, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.comboBox_15 = QtGui.QComboBox(self.groupBox)
        self.comboBox_15.setGeometry(QtCore.QRect(350, 180, 71, 21))
        self.comboBox_15.setObjectName(_fromUtf8("comboBox_15"))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.label_36 = QtGui.QLabel(self.groupBox)
        self.label_36.setGeometry(QtCore.QRect(0, 220, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_13.setGeometry(QtCore.QRect(180, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setText(_fromUtf8(""))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(0, 240, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setGeometry(QtCore.QRect(0, 260, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(180, 240, 21, 17))
        self.checkBox_14.setText(_fromUtf8(""))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(180, 260, 21, 17))
        self.checkBox_15.setText(_fromUtf8(""))
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.label_50 = QtGui.QLabel(self.groupBox)
        self.label_50.setGeometry(QtCore.QRect(230, 240, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_26.setGeometry(QtCore.QRect(340, 240, 91, 16))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.label_51 = QtGui.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(230, 260, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_27.setGeometry(QtCore.QRect(340, 260, 91, 16))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_39 = QtGui.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(0, 280, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(180, 280, 21, 17))
        self.checkBox_16.setText(_fromUtf8(""))
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.label_52 = QtGui.QLabel(self.groupBox)
        self.label_52.setGeometry(QtCore.QRect(230, 280, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_28.setGeometry(QtCore.QRect(340, 280, 91, 16))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.label_40 = QtGui.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(0, 300, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.checkBox_17 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_17.setGeometry(QtCore.QRect(180, 300, 21, 17))
        self.checkBox_17.setText(_fromUtf8(""))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.label_53 = QtGui.QLabel(self.groupBox)
        self.label_53.setGeometry(QtCore.QRect(230, 300, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_29.setGeometry(QtCore.QRect(340, 300, 91, 16))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.label_41 = QtGui.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(0, 320, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_18.setGeometry(QtCore.QRect(180, 320, 21, 17))
        self.checkBox_18.setText(_fromUtf8(""))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.label_54 = QtGui.QLabel(self.groupBox)
        self.label_54.setGeometry(QtCore.QRect(230, 320, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(370, 320, 21, 21))
        self.checkBox_19.setText(_fromUtf8(""))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.label_42 = QtGui.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(0, 340, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_21.setGeometry(QtCore.QRect(100, 340, 113, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.label_55 = QtGui.QLabel(self.groupBox)
        self.label_55.setGeometry(QtCore.QRect(230, 340, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.lineEdit_30 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_30.setGeometry(QtCore.QRect(340, 340, 91, 20))
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.pushButton_26 = QtGui.QPushButton(self.groupBox)
        self.pushButton_26.setGeometry(QtCore.QRect(340, 361, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_3.setGeometry(QtCore.QRect(490, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_4.setGeometry(QtCore.QRect(130, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_5.setGeometry(QtCore.QRect(270, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_6.setGeometry(QtCore.QRect(360, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_7 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 46, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_8 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_8.setGeometry(QtCore.QRect(140, 46, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 10, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textEdit = QtGui.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(0, 80, 771, 311))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.checkBox_9 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_9.setGeometry(QtCore.QRect(30, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 671, 341))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(180, 11, 151, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 60, 151, 31))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 111, 151, 31))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 160, 151, 31))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 220, 151, 31))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.pushButton_20 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 280, 111, 31))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_21.setGeometry(QtCore.QRect(200, 280, 111, 31))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 280, 251, 31))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(160, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(160, 140, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit = QtGui.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(310, 80, 161, 31))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 140, 161, 31))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_5)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_13 = QtGui.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 261, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(50, 80, 641, 291))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8("sud1.png")))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8("Kalp Logo.bmp")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 10, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(740, 10, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(590, 370, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(600, 260, 101, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(70, 260, 511, 33))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.textEdit_3 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(70, 370, 511, 161))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "KALPTECH SOLUTIONS", None))
        self.label_2.setText(_translate("MainWindow", "W H T", None))
        self.checkBox.setText(_translate("MainWindow", "Stop", None))
        self.pushButton.setText(_translate("MainWindow", "Shutdown", None))
        self.label_16.setText(_translate("MainWindow", "Tester Model", None))
        self.label_17.setText(_translate("MainWindow", "S/W Version", None))
        self.label_18.setText(_translate("MainWindow", "Card Status", None))
        self.label_19.setText(_translate("MainWindow", "Cable No", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "01", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "02", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "03", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "04", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "05", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "06", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "07", None))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "08", None))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "09", None))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "10", None))
        self.label_20.setText(_translate("MainWindow", "Cable Name", None))
        self.label_21.setText(_translate("MainWindow", "Operator Code", None))
        self.pushButton_23.setText(_translate("MainWindow", "Scan Data", None))
        self.pushButton_24.setText(_translate("MainWindow", "Enter", None))
        self.pushButton_25.setText(_translate("MainWindow", "Mannual", None))
        self.label_22.setText(_translate("MainWindow", "Cable Status", None))
        self.label_23.setText(_translate("MainWindow", "Pass Count", None))
        self.label_24.setText(_translate("MainWindow", "Vac. Setpoint", None))
        self.label_25.setText(_translate("MainWindow", "Fail Count", None))
        self.label_26.setText(_translate("MainWindow", "Total Count", None))
        self.label_27.setText(_translate("MainWindow", "Vaccum", None))
        self.pushButton_4.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Monitor", None))
        self.label_28.setText(_translate("MainWindow", "Harness Parameter-", None))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Setting File", None))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "Harness File", None))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "Lable File", None))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "Group File", None))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "Barcode1 File", None))
        self.comboBox_16.setItemText(5, _translate("MainWindow", "Barcode2 File", None))
        self.lineEdit_31.setPlaceholderText(_translate("MainWindow", "Select FIle", None))
        self.pushButton_27.setText(_translate("MainWindow", "...", None))
        self.checkBox_20.setText(_translate("MainWindow", "Local Folder", None))
        self.pushButton_28.setText(_translate("MainWindow", "Send File", None))
        self.checkBox_21.setText(_translate("MainWindow", "Current Time", None))
        self.pushButton_29.setText(_translate("MainWindow", "Send Time", None))
        self.label_56.setText(_translate("MainWindow", "ss       mm      hh        wd         dd     mm      yy", None))
        self.label_57.setText(_translate("MainWindow", ":", None))
        self.label_58.setText(_translate("MainWindow", ":", None))
        self.label_59.setText(_translate("MainWindow", ":", None))
        self.label_60.setText(_translate("MainWindow", ":", None))
        self.label_61.setText(_translate("MainWindow", "Vaccume Setpoint", None))
        self.label_62.setText(_translate("MainWindow", "Vaccume High", None))
        self.pushButton_30.setText(_translate("MainWindow", "Printer Test", None))
        self.pushButton_31.setText(_translate("MainWindow", "Scan Data", None))
        self.label_63.setText(_translate("MainWindow", "Vaccume Low", None))
        self.label_29.setText(_translate("MainWindow", "Cable name", None))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "Harness name", None))
        self.label_43.setText(_translate("MainWindow", "Mode", None))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Mannual", None))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Auto", None))
        self.label_30.setText(_translate("MainWindow", "Relay 1 Setting", None))
        self.label_31.setText(_translate("MainWindow", "Relay 2 Setting", None))
        self.label_32.setText(_translate("MainWindow", "Relay 3 Setting", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "On_Fail", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "On_Pass", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "On_Fail", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "On_Pass", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "On_Fail", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "On_Pass", None))
        self.label_44.setText(_translate("MainWindow", "Relay 1 On Time", None))
        self.label_45.setText(_translate("MainWindow", "Relay 2 On Time", None))
        self.label_46.setText(_translate("MainWindow", "Relay 3 On Time", None))
        self.label_33.setText(_translate("MainWindow", "Pass Count", None))
        self.label_47.setText(_translate("MainWindow", "Fail Count", None))
        self.label_34.setText(_translate("MainWindow", "Label Printing", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_48.setText(_translate("MainWindow", "Barcode Scanner", None))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_35.setText(_translate("MainWindow", "Extra Points", None))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_49.setText(_translate("MainWindow", "Two Stage", None))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_36.setText(_translate("MainWindow", "Cutter Module Setting", None))
        self.label_37.setText(_translate("MainWindow", "Open Point Cutter", None))
        self.label_38.setText(_translate("MainWindow", "Short Point Cutter", None))
        self.label_50.setText(_translate("MainWindow", "Waiting Delay", None))
        self.label_51.setText(_translate("MainWindow", "Waiting Delay", None))
        self.label_39.setText(_translate("MainWindow", "Interchange Point", None))
        self.label_52.setText(_translate("MainWindow", "Waiting Delay", None))
        self.label_40.setText(_translate("MainWindow", "Extra point Cutter", None))
        self.label_53.setText(_translate("MainWindow", "Wating Delay", None))
        self.label_41.setText(_translate("MainWindow", "Barcode Matching", None))
        self.label_54.setText(_translate("MainWindow", "Single/Double", None))
        self.label_42.setText(_translate("MainWindow", "Barcode1 Size", None))
        self.label_55.setText(_translate("MainWindow", "Barcode 2 Size", None))
        self.pushButton_26.setText(_translate("MainWindow", "Create File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Teaching", None))
        self.checkBox_2.setText(_translate("MainWindow", "Check Board", None))
        self.checkBox_3.setText(_translate("MainWindow", "Show Points", None))
        self.checkBox_4.setText(_translate("MainWindow", "Check Continuity", None))
        self.checkBox_5.setText(_translate("MainWindow", "Self Test", None))
        self.checkBox_6.setText(_translate("MainWindow", "Learn Harness", None))
        self.checkBox_7.setText(_translate("MainWindow", "Group File", None))
        self.checkBox_8.setText(_translate("MainWindow", "Show Group Points", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save File", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Piboto\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Board Test", None))
        self.checkBox_9.setText(_translate("MainWindow", "Serial Communication", None))
        self.label_7.setText(_translate("MainWindow", "Port", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "/dev/ttyAMA0", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "/dev/ttyprintk", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "/dev/ttyS0", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "9600", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2400", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "4800", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "19200", None))
        self.label_8.setText(_translate("MainWindow", "Baudrate", None))
        self.label_9.setText(_translate("MainWindow", "Parity", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Even", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Odd", None))
        self.label_10.setText(_translate("MainWindow", "Stop bit", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "STOPBITS_ONE", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "None", None))
        self.label_11.setText(_translate("MainWindow", "Data bit", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "EIGHT", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "SEVEN", None))
        self.pushButton_20.setText(_translate("MainWindow", "Connect", None))
        self.pushButton_21.setText(_translate("MainWindow", "Dissconnect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings", None))
        self.label_3.setText(_translate("MainWindow", "USERNAME", None))
        self.label_4.setText(_translate("MainWindow", "PASSWORD", None))
        self.pushButton_2.setText(_translate("MainWindow", "LOGIN", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Login", None))
        self.label_13.setText(_translate("MainWindow", "Software Under devlopment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Database", None))
        self.label_5.setText(_translate("MainWindow", "Date", None))
        self.label_6.setText(_translate("MainWindow", "Time", None))
        self.pushButton_7.setText(_translate("MainWindow", "OK", None))
        self.pushButton_5.setText(_translate("MainWindow", "Browse", None))

